# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "DisUnknown"
description: "The project page for \"DisUnknown: Distilling Unknown Factors for Disentanglement Learning\""

title1: "DisUnknown:"
title2: "Distilling Unknown Factors for Disentanglement Learning"
title3: "International Conference on Computer Vision (ICCV) 2021"
#email: stormraiser2012@gmail.com
author1: "Sitao Xiang"
author1_url: "https://github.com/stormraiser"
author2: "Yuming Gu"
author2_url: "https://yuming-gu.com/"
author3: "Pengda Xiang"
author3_url: ""
author4: "Menglei Chai"
author4_url: "https://mlchai.com/"
author5: "Hao Li"
author5_url: "http://www.hao-li.com/Hao_Li/Hao_Li_-_about_me.html"
author6: "Yajie Zhao"
author6_url: "https://www.yajie-zhao.com/"
author7: "Mingming He"
author7_url: "http://mingminghe.com/"
author_aff0: "1"
author_aff1: "1,2"
author_aff2: "2"
author_aff3: "3"
affliation1: "University of Southern California"
affliation2: "USC Institute for Creative Technologies"
affliation3: "Snap Inc."
thumbnail_paper: "thumbnails/paper.jpg"
thumbnail_code: "thumbnails/code.png"
#thumbnail_supp: "thumbnails/supp.jpg"
url_paper: "https://arxiv.org/abs/2109.08090"
#url_supp: "supps/DisUnknown_supp.pdf"
caption_paper: "Paper"
caption_code: "Code"
#caption_supp: "Supp"
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: StormRaiser123
#github_username:  stormraiser

# Build settings
theme: jekyll-theme-cayman
#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
